alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
envs:
- key: APP_URL
  scope: RUN_AND_BUILD_TIME
  value: https://trade123-l3zp7.ondigitalocean.app
- key: FRONTEND_URL
  scope: RUN_AND_BUILD_TIME
  value: https://trade123-l3zp7.ondigitalocean.app
- key: ENVIRONMENT
  scope: RUN_AND_BUILD_TIME
  value: production
- key: DEPLOYMENT_MODE
  scope: RUN_AND_BUILD_TIME
  value: "true"
- key: DATABASE_URL
  scope: RUN_AND_BUILD_TIME
  value: "placeholder-set-in-digitalocean-env"
- key: DATABASE_HOST
  scope: RUN_AND_BUILD_TIME
  value: "placeholder-set-in-digitalocean-env"
- key: DATABASE_PORT
  scope: RUN_AND_BUILD_TIME
  value: "25060"
- key: DATABASE_NAME
  scope: RUN_AND_BUILD_TIME
  value: defaultdb
- key: DATABASE_USER
  scope: RUN_AND_BUILD_TIME
  value: "placeholder-set-in-digitalocean-env"
- key: DATABASE_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: "placeholder-set-in-digitalocean-env"
- key: DATABASE_SSLMODE
  scope: RUN_AND_BUILD_TIME
  value: require
- key: REDIS_URL
  scope: RUN_AND_BUILD_TIME
  value: "placeholder-set-in-digitalocean-env"
- key: REDIS_HOST
  scope: RUN_AND_BUILD_TIME
  value: "placeholder-set-in-digitalocean-env"
- key: REDIS_PORT
  scope: RUN_AND_BUILD_TIME
  value: "25061"
- key: REDIS_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: "placeholder-set-in-digitalocean-env"
- key: SHAREKHAN_API_KEY
  scope: RUN_AND_BUILD_TIME
  value: "placeholder-set-in-digitalocean-env"
- key: SHAREKHAN_SECRET_KEY
  scope: RUN_AND_BUILD_TIME
  value: "placeholder-set-in-digitalocean-env"
- key: SHAREKHAN_CUSTOMER_ID
  scope: RUN_AND_BUILD_TIME
  value: "placeholder-set-in-digitalocean-env"
- key: ZERODHA_API_KEY
  scope: RUN_AND_BUILD_TIME
  value: "placeholder-set-in-digitalocean-env"
- key: ZERODHA_API_SECRET
  scope: RUN_AND_BUILD_TIME
  value: "placeholder-set-in-digitalocean-env"
- key: TRUEDATA_LOGIN
  scope: RUN_AND_BUILD_TIME
  value: "placeholder-set-in-digitalocean-env"
- key: TRUEDATA_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: "placeholder-set-in-digitalocean-env"
- key: LOG_LEVEL
  scope: RUN_AND_BUILD_TIME
  value: INFO
- key: SECRET_KEY
  scope: RUN_AND_BUILD_TIME
  value: "placeholder-set-in-digitalocean-env"
- key: PYTHONPATH
  scope: RUN_AND_BUILD_TIME
  value: /app
- key: TZ
  scope: RUN_AND_BUILD_TIME
  value: Asia/Kolkata
- key: PAPER_TRADING
  scope: RUN_AND_BUILD_TIME
  value: "true"
- key: MAX_POSITION_SIZE
  scope: RUN_AND_BUILD_TIME
  value: "100000"
- key: MAX_DAILY_LOSS
  scope: RUN_AND_BUILD_TIME
  value: "10000"
- key: EMAIL_NOTIFICATIONS
  scope: RUN_AND_BUILD_TIME
  value: "false"
- key: SMS_NOTIFICATIONS
  scope: RUN_AND_BUILD_TIME
  value: "false"
- key: AUTO_START_TRADING
  scope: RUN_AND_BUILD_TIME
  value: "false"
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "false"
- key: ENABLE_SCHEDULER
  scope: RUN_AND_BUILD_TIME
  value: "true"
- key: SCHEDULER_BUFFER_MINUTES
  scope: RUN_AND_BUILD_TIME
  value: "5"
- key: MAX_WORKERS
  scope: RUN_AND_BUILD_TIME
  value: "4"
- key: AUTONOMOUS_TRADING_ENABLED
  scope: RUN_AND_BUILD_TIME
  value: "false"
- key: ENABLE_CORS
  scope: RUN_AND_BUILD_TIME
  value: "true"
- key: CORS_ORIGINS
  scope: RUN_AND_BUILD_TIME
  value: '["https://trade123-l3zp7.ondigitalocean.app", "http://localhost:3000", "http://localhost:5173", "*"]'
- key: TRUSTED_HOSTS
  scope: RUN_AND_BUILD_TIME
  value: '["trade123-l3zp7.ondigitalocean.app", "*.ondigitalocean.app", "localhost", "*"]'
- key: ENABLE_CORS
  scope: RUN_AND_BUILD_TIME
  value: "true"
- key: ZERODHA_MULTI_USER_ENABLED
  scope: RUN_AND_BUILD_TIME
  value: "true"
- key: ENABLE_WEBHOOK_NOTIFICATIONS
  scope: RUN_AND_BUILD_TIME
  value: "false"
- key: WEBHOOK_URL
  scope: RUN_AND_BUILD_TIME
  value: ""
- key: EMAIL_FROM
  scope: RUN_AND_BUILD_TIME
  value: "trading@algoauto.com"
- key: EMAIL_HOST
  scope: RUN_AND_BUILD_TIME
  value: ""
- key: EMAIL_PORT
  scope: RUN_AND_BUILD_TIME
  value: "587"
- key: EMAIL_USERNAME
  scope: RUN_AND_BUILD_TIME
  value: ""
- key: EMAIL_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: ""
- key: EMAIL_USE_TLS
  scope: RUN_AND_BUILD_TIME
  value: "true"
- key: BACKUP_ENABLED
  scope: RUN_AND_BUILD_TIME
  value: "true"
- key: BACKUP_INTERVAL_HOURS
  scope: RUN_AND_BUILD_TIME
  value: "24"
- key: BACKUP_RETENTION_DAYS
  scope: RUN_AND_BUILD_TIME
  value: "7"
- key: PRODUCTION_MODE
  scope: RUN_AND_BUILD_TIME
  value: "true"
- key: HEALTH_CHECK_URL
  scope: RUN_AND_BUILD_TIME
  value: https://trade123-l3zp7.ondigitalocean.app/health
- key: ENABLE_PERFORMANCE_MONITORING
  scope: RUN_AND_BUILD_TIME
  value: "true"
- key: MONITORING_INTERVAL_SECONDS
  scope: RUN_AND_BUILD_TIME
  value: "60"
- key: JWT_SECRET_KEY
  scope: RUN_AND_BUILD_TIME
  value: "placeholder-set-in-digitalocean-env"
features:
- buildpack-stack=ubuntu-22
functions:
- cors:
    allow_credentials: false
    allow_headers:
    - '*'
    allow_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    allow_origins:
    - '*'
    max_age: "86400"
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: shyamanurag/123trade
  name: cors-handler
  routes:
  - path: /api/cors
    prefix: true
  source_dir: /
ingress:
  rules:
  - component:
      name: frontend
    match:
      path:
        prefix: /
  - component:
      name: api
    match:
      path:
        prefix: /api
  - component:
      name: api
    match:
      path:
        prefix: /docs
  - component:
      name: api
    match:
      path:
        prefix: /redoc
  - component:
      name: api
    match:
      path:
        prefix: /health
  - component:
      name: api
    match:
      path:
        prefix: /auth
  - component:
      name: api
    match:
      path:
        prefix: /v1
  - component:
      name: api
    match:
      path:
        prefix: /sharekhan
  - component:
      name: api
    match:
      path:
        prefix: /ws
  - component:
      name: cors-handler
    match:
      path:
        prefix: /
name: trade123
region: blr
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: shyamanurag/123trade
  health_check:
    failure_threshold: 3
    http_path: /health
    initial_delay_seconds: 60
    period_seconds: 10
    success_threshold: 2
    timeout_seconds: 10
  http_port: 8000
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: api
  run_command: gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:${PORT:-8000} --timeout 120 --access-logfile - --error-logfile -
  source_dir: /
static_sites:
- build_command: cd src/frontend && npm ci && npm run build
  catchall_document: index.html
  environment_slug: node-js
  envs:
  - key: VITE_API_URL
    scope: BUILD_TIME
    value: https://trade123-l3zp7.ondigitalocean.app
  - key: VITE_WS_URL
    scope: BUILD_TIME
    value: wss://trade123-l3zp7.ondigitalocean.app/ws
  - key: VITE_APP_NAME
    scope: BUILD_TIME
    value: Trade123
  - key: VITE_APP_VERSION
    scope: BUILD_TIME
    value: 2.0.0
  - key: VITE_APP_ENV
    scope: BUILD_TIME
    value: production
  github:
    branch: main
    deploy_on_push: true
    repo: shyamanurag/123trade
  name: frontend
  output_dir: dist
  source_dir: /src/frontend 