name: trade123
region: blr
features:
- buildpack-stack=ubuntu-22
envs:
- key: SHAREKHAN_API_KEY
  scope: RUN_AND_BUILD_TIME
  value: 3yraoHgX8z7fpLnKTyXoZKx8ugtLaOBq
- key: SHAREKHAN_SECRET_KEY
  scope: RUN_AND_BUILD_TIME
  value: XxmjJwQ6KM6PrCc5ryRPQYU2KYQz9qz0
- key: SHAREKHAN_CUSTOMER_ID
  scope: RUN_AND_BUILD_TIME
  value: SANURAG1977
- key: DATABASE_HOST
  scope: RUN_AND_BUILD_TIME
  value: app-87875ca6-5b29-4c9e-a19b-9bcde7e2fde3-do-user-23093341-0.g.db.ondigitalocean.com
- key: DATABASE_PORT
  scope: RUN_AND_BUILD_TIME
  value: "25060"
- key: DATABASE_USER
  scope: RUN_AND_BUILD_TIME
  value: doadmin
- key: DATABASE_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: AVNS_tZlUKP7ygb0Nk6D6be-
- key: DATABASE_NAME
  scope: RUN_AND_BUILD_TIME
  value: defaultdb
- key: DATABASE_SSLMODE
  scope: RUN_AND_BUILD_TIME
  value: require
- key: DATABASE_URL
  scope: RUN_AND_BUILD_TIME
  value: postgresql://doadmin:AVNS_tZlUKP7ygb0Nk6D6be-@app-87875ca6-5b29-4c9e-a19b-9bcde7e2fde3-do-user-23093341-0.g.db.ondigitalocean.com:25060/defaultdb?sslmode=require
- key: REDIS_HOST
  scope: RUN_AND_BUILD_TIME
  value: db-valkey-blr1-21204-do-user-23093341-0.g.db.ondigitalocean.com
- key: REDIS_PORT
  scope: RUN_AND_BUILD_TIME
  value: "25061"
- key: REDIS_USER
  scope: RUN_AND_BUILD_TIME
  value: default
- key: REDIS_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: AVNS_wlAv-G38MVYHWXm4DuR
- key: REDIS_URL
  scope: RUN_AND_BUILD_TIME
  value: redis://default:AVNS_wlAv-G38MVYHWXm4DuR@db-valkey-blr1-21204-do-user-23093341-0.g.db.ondigitalocean.com:25061
- key: JWT_SECRET_KEY
  scope: RUN_AND_BUILD_TIME
  value: trade123-jwt-secret-key-2025-production-secure
- key: SECRET_KEY
  scope: RUN_AND_BUILD_TIME
  value: trade123-app-secret-2025-production-secure
- key: APP_URL
  scope: RUN_AND_BUILD_TIME
  value: ${APP_URL}
- key: FRONTEND_URL
  scope: RUN_AND_BUILD_TIME
  value: ${APP_URL}
- key: CORS_ORIGINS
  scope: RUN_AND_BUILD_TIME
  value: ${APP_URL}
- key: TRUSTED_HOSTS
  scope: RUN_AND_BUILD_TIME
  value: ${APP_DOMAIN}
- key: VITE_API_URL
  scope: BUILD_TIME
  value: ${APP_URL}
- key: VITE_WS_URL
  scope: BUILD_TIME
  value: wss://${APP_DOMAIN}/ws
- key: VITE_APP_NAME
  scope: BUILD_TIME
  value: Trade123
services:
- name: api
  source_dir: /
  github:
    repo: shyamanurag/123trade
    branch: main
    deploy_on_push: true
  run_command: gunicorn main:app --host=0.0.0.0 --port=$PORT
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
static_sites:
- name: frontend
  source_dir: /src/frontend
  github:
    repo: shyamanurag/123trade
    branch: main
    deploy_on_push: true
  build_command: npm ci && npm run build
  output_dir: dist
  environment_slug: node-js
  routes:
  - path: /
    name: frontend 