name: seashell-app
region: blr

services:
- name: trading-system-new
  dockerfile_path: Dockerfile
  source_dir: /
  github:
    repo: shyamanurag/trading-system-new
    branch: main
    deploy_on_push: true
  http_port: 8000
  instance_count: 1
  instance_size_slug: apps-d-1vcpu-4gb
  
  # Environment variables - CONFIGURE ACTUAL VALUES IN DIGITALOCEAN DASHBOARD
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: "SET_IN_DIGITALOCEAN_DASHBOARD"
  - key: REDIS_URL
    scope: RUN_AND_BUILD_TIME
    value: "SET_IN_DIGITALOCEAN_DASHBOARD"
  - key: DATABASE_HOST
    scope: RUN_TIME
    value: "SET_IN_DIGITALOCEAN_DASHBOARD"
  - key: DATABASE_PORT
    scope: RUN_TIME
    value: "25060"
  - key: DATABASE_NAME
    scope: RUN_TIME
    value: defaultdb
  - key: DATABASE_USER
    scope: RUN_TIME
    value: doadmin
  - key: DATABASE_PASSWORD
    scope: RUN_TIME
    value: "SET_IN_DIGITALOCEAN_DASHBOARD"
  - key: DATABASE_SSL
    scope: RUN_TIME
    value: require
  - key: JWT_SECRET
    scope: RUN_TIME
    value: K5ewmaPLwWLzqcFa2ne6dLpk_5YbUa1NC-xR9N8ig74TnENXKUnnK1UTs3xcaE8IRIEMYRVSCN-co2vEPTeq9A
  - key: ENCRYPTION_KEY
    scope: RUN_TIME
    value: lulCrXu3nDX6I18WYuPpWcIrgf2IUGAGLS93ZDwczpQ
  - key: APP_PORT
    scope: RUN_TIME
    value: "8000"
  - key: PORT
    scope: RUN_TIME
    value: "8000"
  - key: NODE_ENV
    scope: RUN_TIME
    value: production
  - key: ENVIRONMENT
    scope: RUN_TIME
    value: production
  - key: LOG_LEVEL
    scope: RUN_TIME
    value: INFO
  - key: LOG_FORMAT
    scope: RUN_TIME
    value: json
  - key: ENABLE_CORS
    scope: RUN_TIME
    value: "true"
  - key: ALLOWED_ORIGINS
    scope: RUN_TIME
    value: "*"
  - key: PAPER_TRADING
    scope: RUN_TIME
    value: "false"
  - key: BACKUP_ENABLED
    scope: RUN_TIME
    value: "true"
  - key: ENABLE_METRICS
    scope: RUN_TIME
    value: "true"
  - key: DEBUG
    scope: RUN_TIME
    value: "false"
  - key: MAX_CONNECTIONS
    scope: RUN_TIME
    value: "20"
  - key: POOL_SIZE
    scope: RUN_TIME
    value: "10"
  - key: CACHE_TTL
    scope: RUN_TIME
    value: "300"
  - key: ZERODHA_CLIENT_ID
    scope: RUN_TIME
    value: QSW899
  - key: ZERODHA_API_KEY
    scope: RUN_TIME
    value: sylcoq492qz6f7ej
  - key: ZERODHA_API_SECRET
    scope: RUN_TIME
    value: sylcoq492qz6f7ej
  - key: TRUEDATA_USERNAME
    scope: RUN_TIME
    value: Trial106
  - key: TRUEDATA_PASSWORD
    scope: RUN_TIME
    value: shyam106
  - key: TRUEDATA_PORT
    scope: RUN_TIME
    value: "8086"
  - key: TRUEDATA_URL
    scope: RUN_TIME
    value: push.truedata.in
  - key: TRUEDATA_SANDBOX
    scope: RUN_TIME
    value: "false"
  # Database connection tuning to prevent timeouts
  - key: DATABASE_POOL_SIZE
    scope: RUN_TIME
    value: "5"
  - key: DATABASE_MAX_OVERFLOW
    scope: RUN_TIME
    value: "10"
  - key: DATABASE_POOL_TIMEOUT
    scope: RUN_TIME
    value: "30"
  - key: DATABASE_POOL_RECYCLE
    scope: RUN_TIME
    value: "3600"
  # Redis configuration details - SET IN DIGITALOCEAN DASHBOARD
  - key: REDIS_HOST
    scope: RUN_TIME
    value: "SET_IN_DIGITALOCEAN_DASHBOARD"
  - key: REDIS_PORT
    scope: RUN_TIME
    value: "25061"
  - key: REDIS_PASSWORD
    scope: RUN_TIME
    value: "SET_IN_DIGITALOCEAN_DASHBOARD"
  - key: REDIS_USERNAME
    scope: RUN_TIME
    value: default
  - key: REDIS_SSL
    scope: RUN_TIME
    value: "true"
  # Optional services disabled to prevent errors
  - key: N8N_ENABLED
    scope: RUN_TIME
    value: "false"
  - key: N8N_WEBHOOK_URL
    scope: RUN_TIME
    value: ""
  - key: DATA_PROVIDER_ENABLED
    scope: RUN_TIME
    value: "false"
  - key: DATA_PROVIDER_WEBHOOK_URL
    scope: RUN_TIME
    value: ""
  - key: DATA_PROVIDER_AUTH_TOKEN
    scope: RUN_TIME
    value: ""
  - key: MONITORING_ENABLED
    scope: RUN_TIME
    value: "false"
  - key: TELEGRAM_BOT_TOKEN
    scope: RUN_TIME
    value: ""
  - key: TELEGRAM_CHAT_ID
    scope: RUN_TIME
    value: ""
  - key: EMAIL_USERNAME
    scope: RUN_TIME
    value: ""
  - key: EMAIL_PASSWORD
    scope: RUN_TIME
    value: ""
  - key: EMERGENCY_PHONE_NUMBER
    scope: RUN_TIME
    value: ""
  - key: SUPPORT_EMAIL
    scope: RUN_TIME
    value: support@trading-system.com
  - key: ZERODHA_ACCOUNT_NAME
    scope: RUN_TIME
    value: "Shyam anurag"

# Remove databases section as we're using external DigitalOcean managed databases
# databases:
# - name: db
#   engine: PG
#   version: "14"

features:
- buildpack-stack=ubuntu-22

ingress:
  rules:
  - component:
      name: trading-system-new
    match:
      path:
        prefix: / 