[build]
  publish = "dist/frontend"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://trading-system-fullstack-api.ondigitalocean.app"

[[redirects]]
  from = "/api/*"
  to = "https://trading-system-fullstack-api.ondigitalocean.app/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 