name: trade123
region: blr
services:
- name: api
  source_dir: /
  github:
    repo: shyamanurag/123trade
    branch: main
    deploy_on_push: true
  run_command: gunicorn main:app --host=0.0.0.0 --port=$PORT
  environment_slug: python
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
envs:
- key: SHAREKHAN_API_KEY
  scope: RUN_AND_BUILD_TIME
  value: 3yraoHgX8z7fpLnKTyXoZKx8ugtLaOBq
- key: DATABASE_URL
  scope: RUN_AND_BUILD_TIME
  value: postgresql://doadmin:AVNS_tZlUKP7ygb0Nk6D6be-@app-87875ca6-5b29-4c9e-a19b-9bcde7e2fde3-do-user-23093341-0.g.db.ondigitalocean.com:25060/defaultdb?sslmode=require
- key: SECRET_KEY
  scope: RUN_AND_BUILD_TIME
  value: trade123-secret-key 