name: trading-system
region: blr

services:
- name: api
  environment_slug: python
  github:
    repo: shyamanurag/trading-system-new
    branch: main
    deploy_on_push: true
  
  # Python Configuration - let Dockerfile handle startup
  http_port: 8000
  
  # Instance Configuration  
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  
  # Environment Variables
  envs:
  - key: PORT
    scope: RUN_TIME
    value: "8000"
  - key: ENVIRONMENT
    scope: RUN_TIME  
    value: production
  - key: LOG_LEVEL
    scope: RUN_TIME
    value: info
  - key: PYTHONPATH
    scope: RUN_TIME
    value: /app
  
  # Health Check
  health_check:
    http_path: /health
    initial_delay_seconds: 60
    period_seconds: 10
    timeout_seconds: 5
    failure_threshold: 3
    success_threshold: 1

# Routing Configuration
ingress:
  rules:
  - component:
      name: api
    match:
      path:
        prefix: /

# Alerts
alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED

features:
- buildpack-stack=ubuntu-22 