alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: trading-system-api
    match:
      path:
        prefix: /
name: algoscalper
region: blr
services:
- environment_slug: python
  envs:
  - key: PORT
    scope: RUN_AND_BUILD_TIME
    value: "8000"
  - key: ENVIRONMENT
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: LOG_LEVEL
    scope: RUN_AND_BUILD_TIME
    value: info
  github:
    branch: main
    deploy_on_push: true
    repo: shyamanurag/trading-system-new
  http_port: 8000
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: trading-system-api
  run_command: uvicorn main:app --host 0.0.0.0 --port $PORT
  source_dir: / 