name: algoauto
region: blr

features:
- buildpack-stack=ubuntu-22

services:
  - name: api
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
      repo: shyamanurag/trading-system-new
    http_port: 8000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    source_dir: /
    run_command: |
      export PYTHONPATH=/app && 
      pip install -r requirements.txt && 
      python -m uvicorn main:app --host 0.0.0.0 --port 8000 --workers 1 --timeout-keep-alive 120
    health_check:
      http_path: /health/ready
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      failure_threshold: 3
      success_threshold: 1
    envs:
      - key: PYTHON_VERSION
        scope: RUN_AND_BUILD_TIME
        value: "3.11.2"
      - key: PORT
        scope: RUN_AND_BUILD_TIME
        value: "8000"
      - key: ENVIRONMENT
        scope: RUN_AND_BUILD_TIME
        value: production
      - key: DEBUG
        scope: RUN_AND_BUILD_TIME
        value: "false"
      - key: ENABLE_CORS
        scope: RUN_AND_BUILD_TIME
        value: "true"

static_sites:
  - name: frontend
    github:
      branch: main
      deploy_on_push: true
      repo: shyamanurag/trading-system-new
    source_dir: /src/frontend
    build_command: |
      sudo apt-get update && 
      sudo apt-get install -y curl gnupg && 
      curl -fsSL https://deb.nodesource.com/setup_18.x | sudo bash - && 
      sudo apt-get install -y nodejs && 
      export PATH="/usr/local/bin:$PATH" && 
      sudo npm install -g npm@latest && 
      rm -rf node_modules package-lock.json && 
      npm install --no-optional && 
      npm install @vitejs/plugin-react @rollup/rollup-linux-x64-gnu && 
      npm run build
    output_dir: dist
    index_document: index.html
    catchall_document: index.html
    environment_slug: node-js
    envs:
      - key: VITE_APP_NAME
        scope: BUILD_TIME
        value: AlgoAuto Trading
      - key: VITE_APP_ENV
        scope: BUILD_TIME
        value: production

ingress:
  rules:
  - component:
      name: frontend
    match:
      path:
        prefix: /
  - component:
      name: api
    match:
      path:
        prefix: /api
  - component:
      name: api
    match:
      path:
        prefix: /ws 