apiVersion: v1
kind: Secret
metadata:
  name: trading-system-secrets
  namespace: trading-system
type: Opaque
data:
  # These are base64 encoded values. Replace with actual base64 encoded secrets
  API_KEY: <base64-encoded-api-key>
  API_SECRET: <base64-encoded-api-secret>
  DB_PASSWORD: <base64-encoded-db-password>
  REDIS_PASSWORD: <base64-encoded-redis-password>
  SSL_CERT: <base64-encoded-ssl-cert>
  SSL_KEY: <base64-encoded-ssl-key>
  JWT_SECRET: <base64-encoded-jwt-secret>
  ENCRYPTION_KEY: <base64-encoded-encryption-key> 