"""Additional trading system tables: orders, signals, advanced order types"""
from datetime import datetime
from sqlalchemy import (
    Column, Integer, String, DateTime, DECIMAL, Boolean, JSON, ForeignKey, Index
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from src.config.database import Base

class Order(Base):
    """Comprehensive order management table"""
    __tablename__ = "orders"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    stock_id = Column(Integer, ForeignKey("stocks.id"), nullable=False)
    portfolio_id = Column(Integer, ForeignKey("portfolios.id"), nullable=True)

    side = Column(String(4), nullable=False)  # BUY / SELL
    order_type = Column(String(20), nullable=False)  # MARKET, LIMIT, SL etc.
    quantity = Column(Integer, nullable=False)
    price = Column(DECIMAL(10, 4))  # null for market orders
    status = Column(String(20), default="PENDING")  # PENDING, EXECUTED, CANCELLED
    filled_quantity = Column(Integer, default=0)
    average_price = Column(DECIMAL(10, 4))
    exchange_order_id = Column(String(100))

    validity = Column(String(20), default="DAY")  # DAY, IOC, GTC

    metadata = Column(JSON)

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    __table_args__ = (
        Index("ix_orders_user_status", "user_id", "status"),
    )

class Signal(Base):
    """Strategy signals generated by algorithms"""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, index=True)
    strategy_name = Column(String(50), nullable=False)
    stock_id = Column(Integer, ForeignKey("stocks.id"), nullable=False)
    signal_type = Column(String(10), nullable=False)  # BUY, SELL
    confidence_score = Column(DECIMAL(5, 2))
    timeframe = Column(String(20))
    valid_until = Column(DateTime(timezone=True))
    metadata = Column(JSON)
    status = Column(String(20), default="ACTIVE")  # ACTIVE, EXPIRED, CONSUMED
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class BracketOrder(Base):
    """Advanced bracket order with SL and Target legs"""
    __tablename__ = "bracket_orders"

    id = Column(Integer, primary_key=True, index=True)
    parent_order_id = Column(Integer, ForeignKey("orders.id"), nullable=False)
    stop_loss = Column(DECIMAL(10, 4))
    target_price = Column(DECIMAL(10, 4))
    trailing_stop = Column(DECIMAL(10, 4))
    status = Column(String(20), default="ACTIVE")
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class MultiLegOrder(Base):
    """Complex multi-leg strategies (e.g., option spreads)"""
    __tablename__ = "multi_leg_orders"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    strategy_name = Column(String(50))
    legs = Column(JSON, nullable=False)  # list of leg definitions
    status = Column(String(20), default="PENDING")
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class ConditionalOrder(Base):
    """Orders triggered on specific conditions (price, time, indicator)"""
    __tablename__ = "conditional_orders"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    condition_type = Column(String(30), nullable=False)  # PRICE, TIME, CUSTOM
    condition_expression = Column(String(255), nullable=False)
    linked_order_id = Column(Integer, ForeignKey("orders.id"), nullable=False)
    status = Column(String(20), default="WAITING")  # WAITING, TRIGGERED, CANCELLED
    created_at = Column(DateTime(timezone=True), server_default=func.now())
